#!/bin/bash


if [ $# -ne 1 ]
then
	echo
	echo Brightness Adjust Tool
	echo ----------------------
	echo Adjust screen brightness on Linux/Intel machines. \[Fix for default brightness adjust issue]
	echo Add this file to your path to use it as a command. \'echo \$path\' and add it to one directory.
	echo NOTE: Run command with super user privilege.
    echo
	echo Syntax: sudo brightness \<value\>
	echo Valid brightness value: 1-25. Example:
	echo $ brightness 5
	echo
	
	exit
fi


if [ $1 -lt 1 -o $1 -gt 25 ]
then
	echo
	echo Error: Extreme brightness
	echo Valid brightness value: 1-25
	echo

	exit
fi


BRIGHT=$(( $1 * 100 ))
cd /sys/class/backlight/intel_backlight
echo $BRIGHT > brightness


exit
